language: python
python: 
  - "3.6.10"

stages:
  - name: deploy

jobs:
  include:
    - stage: deploy
      name: Heroku Deploy
      script: /bin/true
      deploy:
        provider: heroku
        api_key:
          secure: "keSb8CYVasN3ISjPehz1pqUBOJtsPLiVDpZjakkKmL1xd3TxvdBNmc494iAz+zhVt2CDauvVpyHZz4F56dVvEFC8EqwtnrtDkbSC5PtEqjLUsvE5BzR199/pJfYPoAGayvlFN20x6Rr7dGXfbvcsxO0JWncPxElySTCKrsOjGg+XVweJBxLosV8cCaTsblefB58gvzs+9X9HQCsWpLIPp9oYb9whKNZGjmk2ne4YHdHPoALEUrD7CMx7SNvKIUf/k8Mab48UP5Of9sF7SwKGVhqhYqs1DkLM9Jzqsqa4IY9gFs+lYlM0HFIaPB8G7qB53hfQ1Q3RQzd1C8hPx17kT+DEKKFfgYuMpqTNHZgqr3TbmZNzGLLJDoBBn0/+8oajEiHRLn2m1UG2YknMNRuHToYcNFPf14Aov3gdu43I7C/jyFuxyOWQTdh+cu5P4HPbH5d1GtvgWls5vtfSbzdgzRt2dPQ08g/bwa201wBeUwXO6ah+2TaSQNcGmHQCfJfEa6wpx+lQqWvz0Yzn9XZaaJS3d0NE2N4va5qGDA6bvtJkzsSHmg167Y2jOQYjN192GIl9ONwPvmP2nfU67SV3LT1DMZNKfBSh761nm5F2iixVtIdfQvVUX4jh/kibvSu/JtJxMjf0Z+4cMb/vWGYVA34Gfua6JDQScd8l+xmrA80="
        app: errorcenter-api
        on: master
        run: "python manage.py migrate"